# Generated by Django 3.2.7 on 2021-12-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Co2web',
            fields=[
                ('url', models.CharField(default='', max_length=10000, primary_key=True, serialize=False)),
                ('co2', models.FloatField()),
                ('green_web', models.BooleanField()),
                ('cleaner_than', models.IntegerField()),
                ('co2_equivalent', models.FloatField()),
                ('sumo_weight', models.FloatField()),
                ('cups', models.IntegerField()),
                ('tree', models.IntegerField()),
                ('energy', models.FloatField()),
                ('car_distance', models.IntegerField()),
            ],
        ),
    ]
