# Generated by Django 3.2.7 on 2021-12-05 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2web',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
    ]
