# Generated by Django 3.2.7 on 2021-12-05 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonWeb', '0004_alter_co2web_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2web',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
