# Generated by Django 3.2.7 on 2021-12-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonWeb', '0006_alter_co2web_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co2web',
            name='date',
        ),
    ]
