# Generated by Django 3.2.7 on 2021-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonWeb', '0010_co2web_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webco2',
            fields=[
                ('url', models.CharField(default='', max_length=10000, primary_key=True, serialize=False)),
                ('co2', models.FloatField()),
                ('date', models.CharField(default='', max_length=100)),
                ('green_web', models.BooleanField()),
                ('cleaner_than', models.IntegerField()),
                ('co2_equivalent', models.FloatField()),
                ('sumo_weight', models.FloatField()),
                ('cups', models.IntegerField()),
                ('tree', models.IntegerField()),
                ('energy', models.FloatField()),
                ('car_distance', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='car_distance',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='cleaner_than',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='co2',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='co2_equivalent',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='cups',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='date',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='green_web',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='sumo_weight',
        ),
        migrations.RemoveField(
            model_name='co2web',
            name='tree',
        ),
    ]
