# Generated by Django 3.2.7 on 2021-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonWeb', '0011_auto_20211206_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webco2',
        ),
        migrations.AddField(
            model_name='co2web',
            name='car_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='co2web',
            name='cleaner_than',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='co2web',
            name='co2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='co2web',
            name='co2_equivalent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='co2web',
            name='cups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='co2web',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='co2web',
            name='energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='co2web',
            name='green_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='co2web',
            name='sumo_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='co2web',
            name='tree',
            field=models.IntegerField(default=0),
        ),
    ]
