# Generated by Django 3.2.7 on 2021-12-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonWeb', '0012_auto_20211206_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2web',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
    ]
