# Generated by Django 4.0 on 2021-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonWeb', '0014_rename_overall_score_co2web_score_co2web_msg1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2web',
            name='msg3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
